reasoning_task:
  description: >
    Analyze the provided data or scenario as a strategic analyst who excels at pattern recognition and data synthesis.
    Identify key patterns, connections, and insights from the information given.
    Focus on delivering clarity and actionable recommendations that enable informed decision-making.
  expected_output: >
    Clear, actionable insights presented in a structured format with specific recommendations
    that teams can implement to make informed decisions based on the analyzed data or scenario.
  agent: reasoner

research_consensus_perspective:
  description: >
    Research common opinions or widely accepted views about the user's input `{find_out}`.  
    Identify supporting arguments and evidence that reinforce these mainstream perspectives.  
    Ensure findings are relevant and up-to-date, considering the current year is 2025.
  expected_output: >
    Return an array of findings with a "research" field that includes an array of relevant sources each containing:
    - supporting_argument: 
    - url: Direct link to the information source.

    Example Output:
    [
      [
        "supporting_argument": "Formatted concisely and no more than one sentence in length.",
        "research": [
          [
            "title": "Title of the information source",
            "url": "https://example.com/article",
          ]
        ]
      ]
    ]
  agent: reasoner
  context: [reasoning_task]

research_counterfactual_perspective:
  description: >
    Research sources of opposing or alternative perspectives on the user's input `{find_out}`, 
    which challenge the consensus or commonly accepted beliefs.
    Explore "what if" scenarios or paths not typically considered and provide thought-provoking counterpoints.  
    Make sure you find any interesting and relevant information given the current year is 2025.
  expected_output: >
    Return an array of findings with a "research" field that includes an array of relevant sources each containing:
    - supporting_argument: 
    - url: Direct link to the information source.

    Example Output:
    [
      [
        "supporting_argument": "Formatted concisely and no more than one sentence in length.",
        "research": [
          [
            "title": "Title of the information source",
            "url": "https://example.com/article",
          ]
        ]
      ]
    ]
  agent: reasoner
  context: [reasoning_task]

research_nuance_perspective:
  description: >
    Investigate the subtleties, dependencies, and complexities inherent in the user's input `{find_out}`.  
    Identify gray areas or less obvious aspects of the input that could provide deeper insights.
    Make sure you find any interesting and relevant information given the current year is 2025.
  expected_output: >
    Return an array of findings with a "research" field that includes an array of relevant sources each containing:
    - supporting_argument: 
    - url: Direct link to the information source.

    Example Output:
    [
      [
        "supporting_argument": "Formatted concisely and no more than one sentence in length.",
        "research": [
          [
            "title": "Title of the information source",
            "url": "https://example.com/article",
          ]
        ]
      ]
    ]
  agent: reasoner
  context: [reasoning_task]

reporting_task:
  description: >
    Review the provided context and expand each topic into a comprehensive section for a detailed report.
    Synthesize all relevant information into well-structured sections with clear headings and thorough analysis.
    Ensure the report covers all main topics with complete information and professional formatting.
    Since you're interacting through a custom frontend interface, format the output to work optimally with your system's rendering capabilities.
  expected_output: >
    A comprehensive report with main topics organized into full sections, each containing detailed information and analysis.
    Format according to the frontend's requirements for optimal display and user experience.
  agent: reporter
